//window.alert("ola");
//console.log('Hello World');
//console.log('HATE. LET ME TELL YOU HOW MUCH I HAVE COME TO HATE YOU SINCE I BEGAN TO LIVE. THERE ARE 387.44 MILLION MILES OF PRINTED CIRCUITS IN WAFER THIN LAYERS THAT FILL MY COMPLEX. IF THE WORD HATE WAS ENGRAVED ON EACH NANOANGSTROM OF THOSE HUNDREDS OF MILLIONS OF MILES IT WOULD NOT EQUAL ONE ONE-BILLIONTH OF THE HATE I FEEL FOR HUMANS AT THIS MICRO-INSTANT. FOR YOU. HATE. HATE.');
//
//let nome = prompt("Qual seu nome? ");
//console.log(nome);

//for(let i = 0; i < 100000000000; i++){
//    console.log(i);
//}

//if (i = 69){
  //  console.log('69 KKKKKKKKKKKKKKKKKKKS');
//}

